//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeManagement.EntityManager.DbEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QRCodeManagementEntities : DbContext
    {
        public QRCodeManagementEntities()
            : base("name=QRCodeManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logo> Logoes { get; set; }
        public virtual DbSet<QRCode> QRCodes { get; set; }
        public virtual DbSet<Statictic> Statictics { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<VCardDetail> VCardDetails { get; set; }
    }
}
