//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeManagement.EntityManager.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QRCode()
        {
            this.Statictics = new HashSet<Statictic>();
            this.VCardDetails = new HashSet<VCardDetail>();
        }
    
        public string Id { get; set; }
        public string Title { get; set; }
        public string TargetUrl { get; set; }
        public string StatisticsUrl { get; set; }
        public string Foreground { get; set; }
        public string Background { get; set; }
        public string EmbedLogo { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string Filename { get; set; }
        public byte QrType { get; set; }
        public bool IsArchived { get; set; }
        public Nullable<int> EmbedLogoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statictic> Statictics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VCardDetail> VCardDetails { get; set; }
    }
}
