//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeManagement.EntityManager.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statictic
    {
        public int Id { get; set; }
        public string QrId { get; set; }
        public string Device { get; set; }
        public string Os { get; set; }
        public string LongTitude { get; set; }
        public string LatTitude { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    
        public virtual QRCode QRCode { get; set; }
    }
}
