//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRCodeManagement.EntityManager.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VCardDetail
    {
        public int Id { get; set; }
        public string QrId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string JobTitle { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string MobileNumber { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string About { get; set; }
        public string ProfileImage { get; set; }
        public string HeaderColor { get; set; }
        public string ButtonColor { get; set; }
    
        public virtual QRCode QRCode { get; set; }
    }
}
