// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace QRCodeManagement.Controllers
{
    public partial class QrManagementController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected QrManagementController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Chart()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Chart);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Archive()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Archive);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ArchiveAndGoToManagePage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArchiveAndGoToManagePage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RestoreAndGoToManagePage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RestoreAndGoToManagePage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAndGoToManagePage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAndGoToManagePage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Restore()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Restore);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Delete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateUrl()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateUrl);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateVCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateVCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateVCard()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateVCard);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreateFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateUrl()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateUrl);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteTemplate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteTemplate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteLogo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteLogo);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public QrManagementController Actions { get { return MVC.QrManagement; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "QrManagement";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "QrManagement";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Chart = "Chart";
            public readonly string Manage = "Manage";
            public readonly string Archive = "Archive";
            public readonly string ArchiveAndGoToManagePage = "ArchiveAndGoToManagePage";
            public readonly string RestoreAndGoToManagePage = "RestoreAndGoToManagePage";
            public readonly string DeleteAndGoToManagePage = "DeleteAndGoToManagePage";
            public readonly string Restore = "Restore";
            public readonly string Delete = "Delete";
            public readonly string Create = "Create";
            public readonly string CreateUrl = "CreateUrl";
            public readonly string CreateVCard = "CreateVCard";
            public readonly string UpdateVCard = "UpdateVCard";
            public readonly string CreateFile = "CreateFile";
            public readonly string UpdateFile = "UpdateFile";
            public readonly string Edit = "Edit";
            public readonly string UpdateUrl = "UpdateUrl";
            public readonly string DeleteTemplate = "DeleteTemplate";
            public readonly string SaveTemplate = "SaveTemplate";
            public readonly string UploadLogo = "UploadLogo";
            public readonly string DeleteLogo = "DeleteLogo";
            public readonly string UploadVcardImage = "UploadVcardImage";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Chart = "Chart";
            public const string Manage = "Manage";
            public const string Archive = "Archive";
            public const string ArchiveAndGoToManagePage = "ArchiveAndGoToManagePage";
            public const string RestoreAndGoToManagePage = "RestoreAndGoToManagePage";
            public const string DeleteAndGoToManagePage = "DeleteAndGoToManagePage";
            public const string Restore = "Restore";
            public const string Delete = "Delete";
            public const string Create = "Create";
            public const string CreateUrl = "CreateUrl";
            public const string CreateVCard = "CreateVCard";
            public const string UpdateVCard = "UpdateVCard";
            public const string CreateFile = "CreateFile";
            public const string UpdateFile = "UpdateFile";
            public const string Edit = "Edit";
            public const string UpdateUrl = "UpdateUrl";
            public const string DeleteTemplate = "DeleteTemplate";
            public const string SaveTemplate = "SaveTemplate";
            public const string UploadLogo = "UploadLogo";
            public const string DeleteLogo = "DeleteLogo";
            public const string UploadVcardImage = "UploadVcardImage";
        }


        static readonly ActionParamsClass_Chart s_params_Chart = new ActionParamsClass_Chart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Chart ChartParams { get { return s_params_Chart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Chart
        {
            public readonly string id = "id";
            public readonly string fromDate = "fromDate";
            public readonly string toDate = "toDate";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Manage s_params_Manage = new ActionParamsClass_Manage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Manage ManageParams { get { return s_params_Manage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Manage
        {
            public readonly string userId = "userId";
            public readonly string page = "page";
            public readonly string keyword = "keyword";
            public readonly string archived = "archived";
        }
        static readonly ActionParamsClass_Archive s_params_Archive = new ActionParamsClass_Archive();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Archive ArchiveParams { get { return s_params_Archive; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Archive
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_ArchiveAndGoToManagePage s_params_ArchiveAndGoToManagePage = new ActionParamsClass_ArchiveAndGoToManagePage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ArchiveAndGoToManagePage ArchiveAndGoToManagePageParams { get { return s_params_ArchiveAndGoToManagePage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ArchiveAndGoToManagePage
        {
            public readonly string qrId = "qrId";
        }
        static readonly ActionParamsClass_RestoreAndGoToManagePage s_params_RestoreAndGoToManagePage = new ActionParamsClass_RestoreAndGoToManagePage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RestoreAndGoToManagePage RestoreAndGoToManagePageParams { get { return s_params_RestoreAndGoToManagePage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RestoreAndGoToManagePage
        {
            public readonly string qrId = "qrId";
        }
        static readonly ActionParamsClass_DeleteAndGoToManagePage s_params_DeleteAndGoToManagePage = new ActionParamsClass_DeleteAndGoToManagePage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAndGoToManagePage DeleteAndGoToManagePageParams { get { return s_params_DeleteAndGoToManagePage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAndGoToManagePage
        {
            public readonly string qrId = "qrId";
        }
        static readonly ActionParamsClass_Restore s_params_Restore = new ActionParamsClass_Restore();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Restore RestoreParams { get { return s_params_Restore; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Restore
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Delete s_params_Delete = new ActionParamsClass_Delete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Delete DeleteParams { get { return s_params_Delete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Delete
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Create s_params_Create = new ActionParamsClass_Create();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Create CreateParams { get { return s_params_Create; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Create
        {
            public readonly string type = "type";
        }
        static readonly ActionParamsClass_CreateUrl s_params_CreateUrl = new ActionParamsClass_CreateUrl();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateUrl CreateUrlParams { get { return s_params_CreateUrl; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateUrl
        {
            public readonly string urlViewModel = "urlViewModel";
        }
        static readonly ActionParamsClass_CreateVCard s_params_CreateVCard = new ActionParamsClass_CreateVCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateVCard CreateVCardParams { get { return s_params_CreateVCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateVCard
        {
            public readonly string vCardViewModel = "vCardViewModel";
        }
        static readonly ActionParamsClass_UpdateVCard s_params_UpdateVCard = new ActionParamsClass_UpdateVCard();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateVCard UpdateVCardParams { get { return s_params_UpdateVCard; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateVCard
        {
            public readonly string vCardViewModel = "vCardViewModel";
        }
        static readonly ActionParamsClass_CreateFile s_params_CreateFile = new ActionParamsClass_CreateFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreateFile CreateFileParams { get { return s_params_CreateFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreateFile
        {
            public readonly string fileViewModel = "fileViewModel";
        }
        static readonly ActionParamsClass_UpdateFile s_params_UpdateFile = new ActionParamsClass_UpdateFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateFile UpdateFileParams { get { return s_params_UpdateFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateFile
        {
            public readonly string fileViewModel = "fileViewModel";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpdateUrl s_params_UpdateUrl = new ActionParamsClass_UpdateUrl();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateUrl UpdateUrlParams { get { return s_params_UpdateUrl; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateUrl
        {
            public readonly string createUrlViewModel = "createUrlViewModel";
        }
        static readonly ActionParamsClass_DeleteTemplate s_params_DeleteTemplate = new ActionParamsClass_DeleteTemplate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteTemplate DeleteTemplateParams { get { return s_params_DeleteTemplate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteTemplate
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteLogo s_params_DeleteLogo = new ActionParamsClass_DeleteLogo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteLogo DeleteLogoParams { get { return s_params_DeleteLogo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteLogo
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Chart = "Chart";
                public readonly string Create = "Create";
                public readonly string Edit = "Edit";
                public readonly string Manage = "Manage";
                public readonly string RawDataChart = "RawDataChart";
                public readonly string ViewVCard = "ViewVCard";
            }
            public readonly string Chart = "~/Views/QrManagement/Chart.cshtml";
            public readonly string Create = "~/Views/QrManagement/Create.cshtml";
            public readonly string Edit = "~/Views/QrManagement/Edit.cshtml";
            public readonly string Manage = "~/Views/QrManagement/Manage.cshtml";
            public readonly string RawDataChart = "~/Views/QrManagement/RawDataChart.cshtml";
            public readonly string ViewVCard = "~/Views/QrManagement/ViewVCard.cshtml";
            static readonly _PartialsClass s_Partials = new _PartialsClass();
            public _PartialsClass Partials { get { return s_Partials; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string CreateFile = "CreateFile";
                    public readonly string CreateUrl = "CreateUrl";
                    public readonly string CreateVCard = "CreateVCard";
                    public readonly string EditFile = "EditFile";
                    public readonly string EditUrl = "EditUrl";
                    public readonly string EditVCard = "EditVCard";
                    public readonly string LogoList = "LogoList";
                    public readonly string QrHiddenField = "QrHiddenField";
                    public readonly string QrListPartial = "QrListPartial";
                    public readonly string QrPreview = "QrPreview";
                    public readonly string QrTemplate = "QrTemplate";
                    public readonly string TemplateList = "TemplateList";
                    public readonly string VCardPreview = "VCardPreview";
                }
                public readonly string CreateFile = "~/Views/QrManagement/Partials/CreateFile.cshtml";
                public readonly string CreateUrl = "~/Views/QrManagement/Partials/CreateUrl.cshtml";
                public readonly string CreateVCard = "~/Views/QrManagement/Partials/CreateVCard.cshtml";
                public readonly string EditFile = "~/Views/QrManagement/Partials/EditFile.cshtml";
                public readonly string EditUrl = "~/Views/QrManagement/Partials/EditUrl.cshtml";
                public readonly string EditVCard = "~/Views/QrManagement/Partials/EditVCard.cshtml";
                public readonly string LogoList = "~/Views/QrManagement/Partials/LogoList.cshtml";
                public readonly string QrHiddenField = "~/Views/QrManagement/Partials/QrHiddenField.cshtml";
                public readonly string QrListPartial = "~/Views/QrManagement/Partials/QrListPartial.cshtml";
                public readonly string QrPreview = "~/Views/QrManagement/Partials/QrPreview.cshtml";
                public readonly string QrTemplate = "~/Views/QrManagement/Partials/QrTemplate.cshtml";
                public readonly string TemplateList = "~/Views/QrManagement/Partials/TemplateList.cshtml";
                public readonly string VCardPreview = "~/Views/QrManagement/Partials/VCardPreview.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_QrManagementController : QRCodeManagement.Controllers.QrManagementController
    {
        public T4MVC_QrManagementController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ChartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, System.DateTime? fromDate, System.DateTime? toDate, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Chart(string id, System.DateTime? fromDate, System.DateTime? toDate, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Chart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fromDate", fromDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "toDate", toDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ChartOverride(callInfo, id, fromDate, toDate, page);
            return callInfo;
        }

        [NonAction]
        partial void ManageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userId, int page, string keyword, bool? archived);

        [NonAction]
        public override System.Web.Mvc.ActionResult Manage(string userId, int page, string keyword, bool? archived)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userId", userId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keyword", keyword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "archived", archived);
            ManageOverride(callInfo, userId, page, keyword, archived);
            return callInfo;
        }

        [NonAction]
        partial void ArchiveOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Archive(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Archive);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ArchiveOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ArchiveAndGoToManagePageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string qrId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ArchiveAndGoToManagePage(string qrId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ArchiveAndGoToManagePage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "qrId", qrId);
            ArchiveAndGoToManagePageOverride(callInfo, qrId);
            return callInfo;
        }

        [NonAction]
        partial void RestoreAndGoToManagePageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string qrId);

        [NonAction]
        public override System.Web.Mvc.ActionResult RestoreAndGoToManagePage(string qrId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RestoreAndGoToManagePage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "qrId", qrId);
            RestoreAndGoToManagePageOverride(callInfo, qrId);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAndGoToManagePageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string qrId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAndGoToManagePage(string qrId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAndGoToManagePage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "qrId", qrId);
            DeleteAndGoToManagePageOverride(callInfo, qrId);
            return callInfo;
        }

        [NonAction]
        partial void RestoreOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Restore(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Restore);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RestoreOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Delete(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Delete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void CreateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int type);

        [NonAction]
        public override System.Web.Mvc.ActionResult Create(int type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Create);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            CreateOverride(callInfo, type);
            return callInfo;
        }

        [NonAction]
        partial void CreateUrlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QRCodeManagement.Models.ViewModels.UrlViewModel urlViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateUrl(QRCodeManagement.Models.ViewModels.UrlViewModel urlViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateUrl);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "urlViewModel", urlViewModel);
            CreateUrlOverride(callInfo, urlViewModel);
            return callInfo;
        }

        [NonAction]
        partial void CreateVCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QRCodeManagement.Models.ViewModels.VCardViewModel vCardViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateVCard(QRCodeManagement.Models.ViewModels.VCardViewModel vCardViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateVCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vCardViewModel", vCardViewModel);
            CreateVCardOverride(callInfo, vCardViewModel);
            return callInfo;
        }

        [NonAction]
        partial void UpdateVCardOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QRCodeManagement.Models.ViewModels.VCardViewModel vCardViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateVCard(QRCodeManagement.Models.ViewModels.VCardViewModel vCardViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateVCard);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vCardViewModel", vCardViewModel);
            UpdateVCardOverride(callInfo, vCardViewModel);
            return callInfo;
        }

        [NonAction]
        partial void CreateFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QRCodeManagement.Models.ViewModels.FileViewModel fileViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreateFile(QRCodeManagement.Models.ViewModels.FileViewModel fileViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileViewModel", fileViewModel);
            CreateFileOverride(callInfo, fileViewModel);
            return callInfo;
        }

        [NonAction]
        partial void UpdateFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QRCodeManagement.Models.ViewModels.FileViewModel fileViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateFile(QRCodeManagement.Models.ViewModels.FileViewModel fileViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileViewModel", fileViewModel);
            UpdateFileOverride(callInfo, fileViewModel);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Edit(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UpdateUrlOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, QRCodeManagement.Models.ViewModels.UrlViewModel createUrlViewModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateUrl(QRCodeManagement.Models.ViewModels.UrlViewModel createUrlViewModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateUrl);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "createUrlViewModel", createUrlViewModel);
            UpdateUrlOverride(callInfo, createUrlViewModel);
            return callInfo;
        }

        [NonAction]
        partial void DeleteTemplateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteTemplate(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteTemplate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteTemplateOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void SaveTemplateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SaveTemplate()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveTemplate);
            SaveTemplateOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UploadLogoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadLogo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadLogo);
            UploadLogoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DeleteLogoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteLogo(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteLogo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteLogoOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UploadVcardImageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UploadVcardImage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UploadVcardImage);
            UploadVcardImageOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
